#!/bin/sh

EPM_VERSION="0.1"

EPM=$(basename $0)
EPM_DIRECTORY=$(dirname $0)

EMACS=${EMACS:-emacs}

usage () {
    echo ""
    echo "$EPM - Emacs Package Manager"
    echo ""
    echo "Usage:"
    echo "    $EPM <command>"
    echo "    $EPM [option]"
    echo ""
    echo "Commands:"
    echo "    list                List installed packages"
    echo "    install             Install a package"
    echo "    delete              Delete a package"
    echo "    refresh             Download package archives"
    echo "    info                Display information about a package"
    echo "    search              Search packages"
    echo ""
    echo "Options:"
    echo "    -h, --help          Display this message"
    echo "    -v, --version       Print version info and exit"
    echo ""
}

epm_execute () {
    epm_op=$1
    shift
    if [ $# -eq 0 ];then
        $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "($epm_op)"
    else
        $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "($epm_op \"$@\")"
    fi
}

list () {
    epm_execute epm-list
}

install () {
    epm_execute epm-install $1
}

delete () {
    epm_execute epm-delete $1
}

refresh () {
    epm_execute package-refresh-contents
}

info () {
    epm_execute epm-info $1
}

search () {
    epm_execute epm-search $1
}

# TODO outdated
# TODO upgrade

COMMAND=$1
case $COMMAND in
    "" | "-h" | "--help")
        usage
        ;;
    "-v" | "--version")
        printf "epm %s\n" $EPM_VERSION
        ;;
    "list" | "install" | "delete" | "refresh" | "info" | "search")
        shift
        ${COMMAND} $@
        ;;
    *)
        echo "Error: Unknown command: ${COMMAND}"
        exit 1
        ;;
esac
